version: "3.8"
services:
  frontend:
    image: docker.io/uppadabhaskar/studentflow-frontend:${IMAGE_TAG:-latest}
    container_name: frontend-container-studentflow
    ports:
      - "3000:80"
    restart: unless-stopped
